[package]
name = "lilypad"
version = "0.1.0"
edition = "2021"

[lib]
name = "lilypad_web"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "lilypad_native"
path = "src/bin.rs"

[profile.release]
lto = true

[dependencies]
druid = "0.8"

# wasm stuff
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.5"
console_error_panic_hook = "0.1"
getrandom = { version = "*", features = ["js"] } # for serde-wasm-bindgen

# general util
once_cell = "1.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# tree sitter
tree-sitter-c2rust = "0.20"

[dependencies.tree-sitter-python]
git = "https://github.com/liamrosenfeld/tree-sitter-python/"
branch = "wasm"
default-features = false
features = ["wasm"]
