[package]
name = "slint-sitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.2.5"
tree-sitter = "0.20.9"

[build-dependencies]
slint-build = "0.2.5"
cc = "*"
